### ISSUE TITLE
"--operationId" still includes service name

### ISSUE THREAD

**Issue by maxoosterveen** [7nohe/openapi-react-query-codegen#133]
**Describe the bug**
When running the generator command with the option `--operationId` still includes the service names in the hooks

**To Reproduce**
`pnpm exec openapi-rq -i ./internal.json --operationId`

**OpenAPI spec file**
If possible, please upload the OpenAPI spec file.

**Expected behavior**
Instead of having the service name in the function hook, I would like it to only use the operation id. `useServiceNameOperationId > useOperationId`

**Screenshots**
If applicable, add screenshots or logs to help explain your problem.

- OS: [e.g. macOS]
- macOS
- Version [e.g. v1.0.0]
- 1.4.1

**Additional context**

**Comment by 7nohe** [comment]
@maxoosterveen 
Thank you for the report. The `--operationId` is an option from `@hey-api/openapi-ts`, but it seems we haven't been able to pass it correctly from our library. I will fix it.

**Comment by JoeHillyard** [comment]
This is blocking for me on migrating over - any pointers on where to start looking?

**Comment by 7nohe** [comment]
@maxoosterveen @JoeHillyard 
Sorry for the delayed response.
The issue has been fixed in #151. A pre-release version has been published, so you can test it by installing the following version.

```bash
npm i -D @7nohe/openapi-react-query-codegen@0.0.0-ef2157e65a33494afbc157e7e72b47353a84e49a
```

If there are no issues, I will merge this PR and release it.

**Comment by JoeHillyard** [comment]
Hmm i don't seem to be having any luck - service name is still coming through

**Comment by nickdaugherty** [comment]
Same - still getting service names when using version `0.0.0-ef2157e65a33494afbc157e7e72b47353a84e49a`

**Comment by 7nohe** [comment]
We have adopted [Flat Services](https://heyapi.vercel.app/openapi-ts/output.html#flat-services) from version 2 to support tree-shaking, and as a result, service names have been deprecated.

**Comment by jappyjan** [comment]
so? how to fix it? the reference to "Flat Services" is absolutely not helpful
